name: better_issue
author: github@j832.com
homepage: https://github.com/kevmoo/better_issue
dependencies:
  angular2: 2.0.0-alpha.46
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
